wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      4: 3.8.5
      5: 0.11.0
      8:
      - 5
best_model_path:
  desc: null
  value: ''
dataset:
  desc: null
  value:
    s3dis:
      label2names:
        '0': ceiling
        '1': floor
        '10': sofa
        '11': board
        '12': clutter
        '2': wall
        '3': beam
        '4': column
        '5': window
        '6': door
        '7': chair
        '8': table
        '9': bookcase
      npydata_root: /media/TrainDataset/Stanford3dDataset_v1.2_Aligned_Version/npy
      rawdata_root: /media/TrainDataset/Stanford3dDataset_v1.2_Aligned_Version
device:
  desc: null
  value: cuda:1
model:
  desc: null
  value:
    dims: 6,4,16,64,128,256,512
    k: 16
n_points:
  desc: null
  value: 4096
num_classes:
  desc: null
  value: 13
test:
  desc: null
  value:
    batch_size: 16
    num_workers: 8
train:
  desc: null
  value:
    aug_loss_weight: 0.1,0.1,0.3,0.5,0.5
    batch_size: 4
    epochs: 100
    lr: 0.01
    num_workers: 8
wandb:
  desc: null
  value: true
